FROM ubuntu:latest
RUN apt-get update -y
RUN apt-get install -y build-essential python3.8 python3.8-dev python3-pip python3.8-venv git
# update pip
RUN python3.8 -m pip install pip --upgrade
RUN python3.8 -m pip install wheel
EXPOSE 80

COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "80"]