# Component Governance Pipeline
# Runs the Feathr code through Component Governance Detection tool and publishes the result under compliance tab.

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'