name: Issue
description: Create an issue or report to help us reproduce and correct the bug
title: '[ISSUE]'

body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an issue. Please refer to our [contribution guide](https://github.com/linkedin/feathr/blob/main/docs/dev_guide/new_contributor_guide.md) for additional information.
        #### Please fill in this issue/bug report template to ensure a timely and thorough response.
  - type: dropdown
    id: contribution
    attributes:
      label: Willingness to contribute
      description: The Feathr Community encourages issue or bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this issue or bug to the Feathr code base?
      options:
        - Yes. I can contribute a fix for this issue or bug independently.
        - Yes. I would be willing to contribute a fix for this issue or bug with guidance from the Feathr community.
        - No. I cannot contribute an issue or bug fix at this time.
    validations:
      required: true

  - type: input
    validations:
      required: false
    attributes:
      label: Feathr version
      description: Feathr version

  - type: textarea
    attributes:
      label: System information
      description: |
        Describe the system where you encountered the issue or bug.
      value: |
        - **OS Platform and Distribution (e.g., Linux Ubuntu 20.0)**:
        - **Python version**:
        - **yarn version, if running the dev UI**:
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the issue
      description: |
        Describe the issue clearly here. Include descriptions of the expected behavior and the actual behavior if it is a bug report.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Tracking information
      description: |
        Please provide the logs and erros for reproducibility.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Code to reproduce issue
      description: |
        Provide a reproducible test case that is the bare minimum necessary to generate the problem.
      placeholder: |
        ```python
        # code to reproduce issue
        ```
    validations:
      required: false
  - type: checkboxes
    id: component
    attributes:
      label: What component(s) does this issue or bug affect?
      description: Please choose one or more components below.
      options:
        - label: "`Python Feathr Client`: This is the client users use to interact with most of our API. Mostly written in Python."
          required: false
        - label: "`Computation Engine`: The computation engine that execute the actual feature join and generation work. Mostly in Scala and Spark."
          required: false
        - label: "`Feature Registry API Layer`: The storage layer supports SQL, Purview(Atlas). The API layer is in Python(FAST API)"
          required: false
        - label: "`Feature Registry Web UI layer`: The Web UI for feature registry. Written in React with a few UI frameworks."
          required: false
