name: Bug Report
description: Create a bug report to help us reproduce and correct the bug
labels: 'bug'
title: '[BUG]'

body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an issue. Please refer to our [contribution guide](https://github.com/linkedin/feathr/blob/main/docs/dev_guide/new_contributor_guide.md) for additional information.
        #### Please fill in this bug report template to ensure a timely and thorough response.
  - type: dropdown
    id: contribution
    attributes:
      label: Willingness to contribute
      description: The Feathr Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this issue or bug to the Feathr code base?
      options:
        - Yes. I can contribute a fix for this bug independently.
        - Yes. I would be willing to contribute a fix for this bug with guidance from the Feathr community.
        - No. I cannot contribute a bug fix at this time.
    validations:
      required: true

  - type: input
    validations:
      required: true
    attributes:
      label: Feathr version
      description: Feathr version

  - type: textarea
    attributes:
      label: System information
      description: |
        Describe the system where you encountered the bug.
      value: |
        - **OS Platform and Distribution (e.g., Linux Ubuntu 20.0)**:
        - **Python version**:
        - **Spark version, if reporting runtime issue**:
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the problem
      description: |
        Describe the problem clearly here. Include descriptions of the expected behavior and the actual behavior if it is a bug report.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Tracking information
      description: |
        Please provide the logs and errors for reproducibility.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Code to reproduce bug
      description: |
        Provide a reproducible test case that is the bare minimum necessary to generate the problem.
      placeholder: |
        ```python
        # code to reproduce bug
        ```
    validations:
      required: false
  - type: checkboxes
    id: component
    attributes:
      label: What component(s) does this bug affect?
      description: Please choose one or more components below.
      options:
        - label: "`Python Client`: This is the client users use to interact with most of our API. Mostly written in Python."
          required: false
        - label: "`Computation Engine`: The computation engine that execute the actual feature join and generation work. Mostly in Scala and Spark."
          required: false
        - label: "`Feature Registry API`: The frontend API layer supports SQL, Purview(Atlas) as storage. The API layer is in Python(FAST API)"
          required: false
        - label: "`Feature Registry Web UI`: The Web UI for feature registry. Written in React"
          required: false
