name: Feature Request
description: Use this template for feature requests.
labels: 'feature'
title: '[FR]'

body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an issue. Please refer to our [contribution guide](https://github.com/feathr-ai/feathr/blob/main/docs/dev_guide/new_contributor_guide.md) for additional information.
        #### Please fill in this bug report template to ensure a timely and thorough response.
  - type: dropdown
    id: contribution
    attributes:
      label: Willingness to contribute
      description: The Feathr Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this issue or bug to the Feathr code base?
      options:
        - Yes. I can contribute a fix for this bug independently.
        - Yes. I would be willing to contribute a fix for this bug with guidance from the Feathr community.
        - No. I cannot contribute a bug fix at this time.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Feature Request Proposal
      description: |
        Provide a clear high-level description of feature request proposal
    validations:
      required: true

  - type: textarea
    attributes:
      label: Motivation
      description: |
        What would this Feature request help Feathr users?
      value: |
        > #### What is the use case for this feature?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Details
      description: |
        Please provide a clear description here.
    validations:
      required: false

  - type: checkboxes
    id: component
    attributes:
      label: What component(s) does this feature request affect?
      description: Please choose one or more components below.
      options:
        - label: "`Python Client`: This is the client users use to interact with most of our API. Mostly written in Python."
          required: false
        - label: "`Computation Engine`: The computation engine that execute the actual feature join and generation work. Mostly in Scala and Spark."
          required: false
        - label: "`Feature Registry API`: The frontend API layer supports SQL, Purview(Atlas) as storage. The API layer is in Python(FAST API)"
          required: false
        - label: "`Feature Registry Web UI`: The Web UI for feature registry. Written in React"
          required: false
