name: Non-technical Request
description: Use this template for non-technical requests
labels: ['non-technical']
title: '[NT]'

body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an issue. Please refer to our [contribution guide](https://github.com/linkedin/feathr/blob/main/docs/dev_guide/new_contributor_guide.md) for additional information.
        #### Please fill in this non-technical template to ensure a timely and thorough response.
  - type: dropdown
    id: contribution
    attributes:
      label: Willingness to contribute
      description: The Feathr Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this issue or bug to the Feathr code base?
      options:
        - Yes. I can contribute for this issue independently.
        - Yes. I would be willing to contribute to this for with guidance from the Feathr community.
        - No. I cannot contribute to this at this time.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Non-technical Request Proposal
      description: |
        Please provide a clear description of the request
    validations:
      required: true
