insert into userroles (project_name, user_name, role_name, create_by, create_reason, create_time) values ('global', 'abc@microsoft.com','admin', 'test_data@microsoft.com', 'test data',  getutcdate())
insert into userroles (project_name, user_name, role_name, create_by, create_reason, create_time) values ('global', 'efg@microsoft.com','admin', 'test_data@microsoft.com', 'test data',  getutcdate())
insert into userroles (project_name, user_name, role_name, create_by, create_reason, create_time) values ('feathr_ci_registry_12_33_182947', 'efg@microsoft.com','admin','test_data@microsoft.com',  'test data',  getutcdate())
insert into userroles (project_name, user_name, role_name, create_by, create_reason, create_time) values ('feathr_ci_registry_12_33_182947', 'hij@microsoft.com','consumer', 'test_data@microsoft.com', 'test data',  getutcdate())
 
insert into access (project_name, access_name) values ('feathr_ci_registry_12_33_182947', 'read')
insert into access (project_name, access_name) values ('feathr_ci_registry_12_33_182947', 'write')
insert into access (project_name, access_name) values ('feathr_ci_registry_12_33_182947', 'manage')
insert into access (project_name, access_name) values ('global', 'read')
insert into access (project_name, access_name) values ('global', 'write')
insert into access (project_name, access_name) values ('global', 'manage')
 
insert into roleaccess (role_name, access_name) values ('admin', 'read')
insert into roleaccess (role_name, access_name) values ('admin', 'write')
insert into roleaccess (role_name, access_name) values ('admin', 'manage')
insert into roleaccess (role_name, access_name) values ('contributor', 'read')
insert into roleaccess (role_name, access_name) values ('contributor', 'write')
insert into roleaccess (role_name, access_name) values ('viewer', 'read')
insert into roleaccess (role_name, access_name) values ('default', '')