remote_theme: just-the-docs/just-the-docs

collections:
  concepts:
    permalink: "/docs/concepts"
    output: true
  dev_guide:
    permalink: "./dev_guide"
    output: true
  how-to-guides:
    permalink: "/how-to-guides"
    output: true
    
just_the_docs:
  collections:
    concepts:
      name: Documentation
    how-to-guides:
      name: Tutorials
