# This workflow builds the docker container and publishes to dockerhub with appropriate tag
# It has two triggers, 
#   1. daily i.e. runs everyday at specific time.
#   2. Anytime a new branch is created under releases

name: Publish Feathr Docker image to DockerHub

on:
  workflow_dispatch: 
  schedule:
    # Runs daily at 10 PM UTC, would generate nightly tag
    - cron: '00 22 * * *'
    

  push:
    # For every push against the releases/** branch, usually would happen at release time, Tag example - releases/v0.7.0
    branches:
      - 'releases/**'


jobs:

  # Deploy the docker container to the three test environments for feathr
  deploy:
    runs-on: ubuntu-latest
    
    
    steps:
      - name: Deploy to Feathr Purview Registry Azure Web App
        id: deploy-to-purview-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'feathr-purview-registry'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FEATHR_PURVIEW_REGISTRY }}
          images: 'feathrfeaturestore/feathr-registry:nightly'

