# This workflow builds the docker container and publishes to dockerhub with appropriate tag
# It has two triggers, 
#   1. daily i.e. runs everyday at specific time.
#   2. Anytime a new branch is created under releases

name: Publish Feathr Docker image to DockerHub

on:
  push:
    # For every push against the releases/** branch, usually would happen at release time, Tag example - releases/v0.7.0
    branches:
      - 'releases/**'
  workflow_dispatch:


jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: feathrfeaturestore/feathr-registry
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: FeathrRegistry.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs: push_to_registry

    
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v4
        with:
          app-name: 'rjrijaiwebapp'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'index.docker.io/feathrfeaturestore/feathr-registry:nightly'