name: Feathr UI Lint and Format Checks

on:
  push:
    branches: [main]
    paths:
      - "ui/**/*"

  pull_request:
    branches: [main]
    paths:
      - "ui/**/*"


jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-eslint@v1
        with:
          eslint_flags: "src/"
          reporter: github-pr-review
          workdir: ui

  prettier:
    name: prettier_code_formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Check out the repository first.
      - uses: actionsx/prettier@v2
        with:
          # prettier CLI arguments.
          args: --check ./ui/src
